// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/RecordingAllVariants.tsx": () => import("../components/mockups/RecordingAllVariants.tsx"),
  "./components/mockups/RecordingCurrent.tsx": () => import("../components/mockups/RecordingCurrent.tsx"),
  "./components/mockups/RecordingVariantA.tsx": () => import("../components/mockups/RecordingVariantA.tsx"),
  "./components/mockups/RecordingVariantB.tsx": () => import("../components/mockups/RecordingVariantB.tsx"),
  "./components/mockups/RecordingVariantC.tsx": () => import("../components/mockups/RecordingVariantC.tsx")
};
